name: muckaloo
favicon: null
layout_spectrum: 1
typography_spectrum: 0.33503
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E8E595'
    - '#D0A825'
    - '#40627C'
    - '#26393D'
    - '#FFFAE4'
  brandStrength: 0.5
  lightness: 0.41058651078492403
  saturation: 0.5
  rhythmicContrast: 0.19903921778313816
purpose: []
